version: '3.8'
services:
  mysql-utilities:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - shared_network        # Add this line
    environment:
      MYSQL_ROOT_PASSWORD: batata
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  shared_network:             # Add these lines
    external: true
    
